kadai06/photoidentify/photoidentify/urls.py
from django.urls import path
from prediction.views import predict

urlpatterns = [
    path('', predict, name='predict'),
]

kadai06/photoidentify/prediction/models.py
from django.db import models

# Create your models here.

kadai06/photoidentify/prediction/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

kadai06/photoidentify/prediction/views.py
from django.shortcuts import render
from .forms import ImageUploadForm
from django.conf import settings
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.applications.vgg16 import decode_predictions
#このvgg16の２つが前と異なる部分
from io import BytesIO
import os
import pandas as pd

def predict(request):
    if request.method == 'GET':
        form = ImageUploadForm()
        return render(request, 'home.html', {'form': form})
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            img_file = form.cleaned_data['image']
            img_file = BytesIO(img_file.read())
            img = load_img(img_file, target_size=(224, 224)) #ここでモデルに合わせてサイズ変更
            img_array = img_to_array(img)
            img_array = img_array.reshape((1, 224, 224, 3)) #ここで配列を4次元に変更
            img_array = preprocess_input(img_array)  #VGG16に対する前処理
            model_path = os.path.join(settings.BASE_DIR, 'prediction', 'models', 'vgg16.h5')
            model = load_model(model_path)
            result = model.predict(img_array)
            prediction_top5 = decode_predictions(result)[0]
            df_Prediction_Top5 = pd.DataFrame(prediction_top5,columns=['ClassID', 'Label', 'Probability']) 
            df_Prediction_Top5["Probability"] = df_Prediction_Top5["Probability"]*100
            dict_prediction_top5 = df_Prediction_Top5.to_dict(orient='records')
            #format_prediction_top5 = [prediction_top5[0][1]]
            #df_Prediction_Top5 = pd.DataFrame(prediction_top5[0],columns=['Class ID', 'Label', 'Probability']) 
            #return render(request, 'home.html', {'form': form, 'prediction': format_prediction_top5})
            #途中で「print(df_Prediction_Top5.columns)」とかをやりたいときは通常どうすればいいのか？
            img_data = request.POST.get('img_data')

            return render(request, 'home.html', {'form': form, 'prediction': dict_prediction_top5,'img_data': img_data})
        else:
            form = ImageUploadForm()
            return render(request, 'home.html', {'form': form})

kadai06/photoidentify/prediction/templates/home.html
<!DOCTYPE html>
<html lang="jp">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>画像判定アプリ</title>
  <style>
    table {
        margin: auto; /* テーブルを中央揃え */
        border-collapse: collapse;
    }
    th, td {
        padding: 10px;
        border: 1px solid black;
    }
</style>
</head>

<body>
 <div class="container py-5 text-center">
  <h2 calss="mb-4">画像判定します</h2>
  <form method="post" enctype="multipart/form-data">
  <div class="mb-3">
    {% csrf_token %}
    {{ form.as_p }}
    <input id="img_data" type="hidden" name="img_data" />
  </div>
    <img id="preview" style="display: none;" class="img-fluid mb-3"/>
    <br>
    <button type="submit" class="btn btn-primary btn-lg">判定</button>
  </form>

  {% if prediction %}
    <div id="prediction">
      <hr>
      <h2 class="mb-4">判定結果</h2>
      <p>あなたのアップロードした画像の判定結果は以下の通りです。</p>
      <ul>
      <!-- {%for row in prediction %}
            <li> {{row.Label}}:{{row.Probability}}</li>
            {% endfor %}
      -->
      <div class="container py-5">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h3 class="mb-0">Prediction Results</h3>
            </div>
            <div class="card-body">
                <table class="table table-striped table-bordered table-hover table-responsive">
                    <thead class="table-dark">
                      <tr>
                          <th>カテゴリ</th>
                          <th>確率</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for row in prediction %}
                      <tr>
                          <td>{{ row.Label }}</td>
                          <td>{{ row.Probability }} %</td>
                      </tr>
            {% endfor %}
        </tbody>
       </table>
      </div>
      </ul>
      <img src="{{ img_data }}" class="img-fluid mb-3"> 
    </div>
  {% endif %}
 </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   <script>
      $(function() {
            $('#id_image').on('change', function() {
            var reader = new FileReader();
            reader.onload = function () {
                $("#preview").attr('src', reader.result);
                $("#preview").show();
                $("#img_data").val(reader.result);
            }
            reader.readAsDataURL(this.files[0]);
             $("#prediction").text('');
            });
        });
      </script>
</body>
</html>